# [START cloudbuild]
steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: 
   - 'install'
   - '-Dmaven.test.skip=true'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  dir: 'webgoat-server'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hello-webgoat:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  dir: 'webgoat-server'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/hello-webgoat:$SHORT_SHA'
# [END cloudbuild]
