apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cloudbuild
  labels:
    app: hello-webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-webgoat
  template:
    metadata:
      labels:
        app: hello-webgoat
    spec:
      containers:
      - name: hello-cloudbuild
        image: gcr.io/GOOGLE_CLOUD_PROJECT/hello-webgoat:COMMIT_SHA
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-cloudbuild
spec:
  selector:
    app: hello-webgoat
  ports:
  - protocol: TCP
    port: 404
    targetPort: 8080
  type: LoadBalancer
